name: ClusterChunk
main: com.CC.General.onStartup
version: 1.3
commands:
  party:
    description: the party command
    usage: test
    permission: test.testietest
  friend:
    description: Adds friends
    usage: /<command> [player]
  enemy:
    description: Adds enemies
    usage: /<command> [enemy]
  relation:
    description: shows your relations whit other players
    usage: /<command>
  endgame:
    description: Only for Staff Members
  rep:
    description: Check your friend's reputation