# Because I thought this would be an epic place for a config file :D
mysql:
  host: localhost
  port: 3306
  database: ClusterChunk
  username: root
  password: root
amount-of-games: 1
game-world-prefix: 'CC'
  